-- Vigil: schema + synthetic data (all data is synthetic; no production data)
CREATE DATABASE IF NOT EXISTS VIGIL;
CREATE SCHEMA IF NOT EXISTS VIGIL.CORE;
USE SCHEMA VIGIL.CORE;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE TABLE CUSTOMERS (CUSTOMER_ID STRING PRIMARY KEY, FULL_NAME STRING, RISK_SEGMENT STRING, KYC_STATUS STRING, ONBOARDED_DATE DATE, COUNTRY STRING);
CREATE OR REPLACE TABLE ACCOUNTS (ACCOUNT_ID STRING PRIMARY KEY, CUSTOMER_ID STRING, ACCOUNT_TYPE STRING, OPENED_DATE DATE, STATUS STRING);
CREATE OR REPLACE TABLE TRANSACTIONS (TRANSACTION_ID STRING PRIMARY KEY, ACCOUNT_ID STRING, TRANSACTION_DATE TIMESTAMP_NTZ, AMOUNT NUMBER(14,2), CURRENCY STRING, TRANSACTION_TYPE STRING, COUNTERPARTY_NAME STRING, COUNTERPARTY_COUNTRY STRING, CHANNEL STRING, IS_FLAGGED BOOLEAN, FLAG_REASON STRING);
CREATE OR REPLACE TABLE ALERTS (ALERT_ID STRING PRIMARY KEY, TRANSACTION_ID STRING, ALERT_TYPE STRING, SEVERITY STRING, CREATED_AT TIMESTAMP_NTZ, STATUS STRING);
CREATE OR REPLACE TABLE LIQUIDITY_SNAPSHOTS (SNAPSHOT_DATE DATE PRIMARY KEY, HQLA_AMOUNT NUMBER(18,2), NET_CASH_OUTFLOWS_30D NUMBER(18,2), LCR_RATIO NUMBER(8,2), STATUS STRING);
CREATE OR REPLACE TABLE CREDIT_PROFILES (LOAN_ACCOUNT_ID STRING PRIMARY KEY, CUSTOMER_ID STRING, OUTSTANDING_AMOUNT NUMBER(14,2), DAYS_PAST_DUE INT, CREDIT_SCORE INT, NPA_FLAG BOOLEAN, AS_OF_DATE DATE);

-- 60 customers, one account each (CUST-000n <-> ACC-000n)
INSERT INTO CUSTOMERS
SELECT 'CUST-'||LPAD(i,4,'0'),
  GET(ARRAY_CONSTRUCT('Aarav','Priya','Rohan','Ananya','Vikram','Kavya','Arjun','Meera','Karan','Divya','Suresh','Neha'),MOD(i,12))::STRING||' '||GET(ARRAY_CONSTRUCT('Sharma','Iyer','Reddy','Nair','Gupta'),MOD(FLOOR(i/12),5))::STRING,
  CASE WHEN i IN (12,19) OR MOD(i,10)=9 THEN 'HIGH' WHEN MOD(i,10)<6 THEN 'LOW' ELSE 'MEDIUM' END,
  CASE WHEN MOD(i,13)=0 THEN 'EXPIRED' WHEN MOD(i,7)=0 THEN 'PENDING' ELSE 'VERIFIED' END,
  DATEADD('day',-(200+MOD(ABS(HASH(i,11)),1500)),'2026-09-28'::DATE),'India'
FROM (SELECT SEQ4()+1 i FROM TABLE(GENERATOR(ROWCOUNT=>60)));

INSERT INTO ACCOUNTS
SELECT 'ACC-'||LPAD(i,4,'0'),'CUST-'||LPAD(i,4,'0'),IFF(MOD(i,2)=0,'SAVINGS','CURRENT'),DATEADD('day',-(100+MOD(ABS(HASH(i,12)),1200)),'2026-09-28'::DATE),'ACTIVE'
FROM (SELECT SEQ4()+1 i FROM TABLE(GENERATOR(ROWCOUNT=>60)));

-- 600 baseline transactions (INR 500-90,500, spread over 72 days, ordinary merchants)
INSERT INTO TRANSACTIONS
WITH b AS (SELECT SEQ4()+1 i, MOD(ABS(HASH(SEQ4()+1,3)),10) t FROM TABLE(GENERATOR(ROWCOUNT=>600)))
SELECT 'TXN-'||LPAD(i,6,'0'),'ACC-'||LPAD(1+MOD(ABS(HASH(i,1)),60),4,'0'),
  DATEADD('minute',MOD(ABS(HASH(i,2)),72*24*60),'2026-07-15 00:00:00'::TIMESTAMP_NTZ),
  500+MOD(ABS(HASH(i,4)),90000),'INR',
  CASE WHEN t<6 THEN 'TRANSFER' WHEN t<8 THEN 'DEPOSIT' ELSE 'WITHDRAWAL' END,
  IFF(t<6,GET(ARRAY_CONSTRUCT('Amazon India','Flipkart','Swiggy','Zomato','Reliance Retail','Big Bazaar','Airtel','Jio','Uber India','BookMyShow','IRCTC','Myntra'),MOD(ABS(HASH(i,5)),12))::STRING,NULL),
  IFF(t<6,'India',NULL),
  CASE WHEN t<6 THEN GET(ARRAY_CONSTRUCT('ONLINE','MOBILE'),MOD(i,2))::STRING WHEN t<8 THEN 'BRANCH' ELSE 'ATM' END,
  FALSE,NULL
FROM b;

-- Seeded pattern: structuring (ACC-0007)
INSERT INTO TRANSACTIONS VALUES
('TXN-ST-01','ACC-0007','2026-09-03 11:05:00',188000,'INR','DEPOSIT',NULL,NULL,'BRANCH',TRUE,'STRUCTURING_SUSPECTED'),
('TXN-ST-02','ACC-0007','2026-09-05 14:20:00',192000,'INR','DEPOSIT',NULL,NULL,'BRANCH',TRUE,'STRUCTURING_SUSPECTED'),
('TXN-ST-03','ACC-0007','2026-09-08 10:40:00',185000,'INR','DEPOSIT',NULL,NULL,'BRANCH',TRUE,'STRUCTURING_SUSPECTED'),
('TXN-ST-04','ACC-0007','2026-09-10 16:10:00',195000,'INR','DEPOSIT',NULL,NULL,'BRANCH',TRUE,'STRUCTURING_SUSPECTED');
-- Seeded pattern: high-risk country remittance (ACC-0012)
INSERT INTO TRANSACTIONS VALUES
('TXN-HR-01','ACC-0012','2026-09-11 11:20:00',650000,'INR','REMITTANCE','Golden Lotus Trading Co','Myanmar','ONLINE',TRUE,'HIGH_RISK_COUNTRY');
-- Seeded pattern: velocity (ACC-0019): 650,000 of 750,000 (86.7%) out within 21h15m
INSERT INTO TRANSACTIONS VALUES
('TXN-VE-01','ACC-0019','2026-09-20 09:30:00',750000,'INR','DEPOSIT',NULL,NULL,'BRANCH',TRUE,'VELOCITY'),
('TXN-VE-02','ACC-0019','2026-09-20 15:10:00',400000,'INR','TRANSFER','Sunrise Traders','India','ONLINE',TRUE,'VELOCITY'),
('TXN-VE-03','ACC-0019','2026-09-21 06:45:00',250000,'INR','TRANSFER','Sunrise Traders','India','ONLINE',TRUE,'VELOCITY');
-- Seeded pattern: RING. 5 different accounts, each unflagged, same counterparty within 72h
INSERT INTO TRANSACTIONS VALUES
('TXN-RG-01','ACC-0031','2026-09-14 10:00:00',42000,'INR','TRANSFER','Zenith Global Ventures','India','ONLINE',FALSE,NULL),
('TXN-RG-02','ACC-0032','2026-09-14 22:30:00',47500,'INR','TRANSFER','Zenith Global Ventures','India','MOBILE',FALSE,NULL),
('TXN-RG-03','ACC-0033','2026-09-15 09:15:00',39800,'INR','TRANSFER','Zenith Global Ventures','India','ONLINE',FALSE,NULL),
('TXN-RG-04','ACC-0034','2026-09-15 18:40:00',51200,'INR','TRANSFER','Zenith Global Ventures','India','MOBILE',FALSE,NULL),
('TXN-RG-05','ACC-0035','2026-09-16 07:05:00',44600,'INR','TRANSFER','Zenith Global Ventures','India','ONLINE',FALSE,NULL);
-- Noise control: 25 unrelated accounts pay a utility in the same 72h window
INSERT INTO TRANSACTIONS
SELECT 'TXN-UT-'||LPAD(n,2,'0'),'ACC-'||LPAD(35+n,4,'0'),
  DATEADD('minute',MOD(ABS(HASH(n,21)),72*60),'2026-09-14 08:00:00'::TIMESTAMP_NTZ),
  800+MOD(ABS(HASH(n,22)),4000),'INR','TRANSFER','Bangalore Electricity Board','India','ONLINE',FALSE,NULL
FROM (SELECT SEQ4()+1 n FROM TABLE(GENERATOR(ROWCOUNT=>25)));

-- Alerts emulate the upstream fraud engine (flagged transactions only; the ring is NOT alerted)
INSERT INTO ALERTS
SELECT 'ALT-'||LPAD(ROW_NUMBER() OVER (ORDER BY TRANSACTION_ID),3,'0'),TRANSACTION_ID,FLAG_REASON,
  IFF(FLAG_REASON='VELOCITY','MEDIUM','HIGH'),DATEADD('hour',1,TRANSACTION_DATE),'OPEN'
FROM TRANSACTIONS WHERE IS_FLAGGED;

-- 30 daily LCR snapshots; day 18 breaches (94%)
INSERT INTO LIQUIDITY_SNAPSHOTS
SELECT DATEADD('day',i-30,'2026-09-29'::DATE),
  ROUND((9500000000+MOD(ABS(HASH(i,31)),1000000000))*IFF(i=18,0.94,1.06+MOD(ABS(HASH(i,32)),100)/1000),2),
  9500000000+MOD(ABS(HASH(i,31)),1000000000),0,'X'
FROM (SELECT SEQ4()+1 i FROM TABLE(GENERATOR(ROWCOUNT=>30)));
UPDATE LIQUIDITY_SNAPSHOTS SET LCR_RATIO=ROUND(100*HQLA_AMOUNT/NET_CASH_OUTFLOWS_30D,2), STATUS=IFF(100*HQLA_AMOUNT/NET_CASH_OUTFLOWS_30D>=100,'COMPLIANT','BREACH');

-- 40 credit profiles; LN-0025 is NPA (120 DPD), LN-0033 is a near-miss (88 DPD)
INSERT INTO CREDIT_PROFILES
SELECT 'LN-'||LPAD(i,4,'0'),'CUST-'||LPAD(i,4,'0'),200000+MOD(ABS(HASH(i,41)),4800000),
  CASE WHEN i=25 THEN 120 WHEN i=33 THEN 88 WHEN i IN (5,14,22) THEN 30+MOD(i,15) ELSE 0 END,
  IFF(i=25,512,550+MOD(ABS(HASH(i,42)),300)),FALSE,'2026-09-28'::DATE
FROM (SELECT SEQ4()+1 i FROM TABLE(GENERATOR(ROWCOUNT=>40)));
UPDATE CREDIT_PROFILES SET NPA_FLAG = DAYS_PAST_DUE > 90;

-- Graph layer. Hub filter: counterparties paid by more than 8 distinct accounts are not evidence of a link
CREATE OR REPLACE DYNAMIC TABLE RING_EDGES TARGET_LAG='1 hour' WAREHOUSE=COMPUTE_WH AS
WITH hubs AS (SELECT COUNTERPARTY_NAME FROM TRANSACTIONS WHERE COUNTERPARTY_NAME IS NOT NULL GROUP BY 1 HAVING COUNT(DISTINCT ACCOUNT_ID)>8)
SELECT a.ACCOUNT_ID ACCOUNT_A, b.ACCOUNT_ID ACCOUNT_B, 'COUNTERPARTY_72H' SHARED_ATTRIBUTE, a.COUNTERPARTY_NAME SHARED_VALUE, COUNT(*) LINK_STRENGTH
FROM TRANSACTIONS a JOIN TRANSACTIONS b ON a.COUNTERPARTY_NAME=b.COUNTERPARTY_NAME AND a.ACCOUNT_ID<b.ACCOUNT_ID AND ABS(DATEDIFF('hour',a.TRANSACTION_DATE,b.TRANSACTION_DATE))<=72
WHERE a.COUNTERPARTY_NAME IS NOT NULL AND a.COUNTERPARTY_NAME NOT IN (SELECT COUNTERPARTY_NAME FROM hubs)
GROUP BY 1,2,3,4;

-- Connected components by 4 rounds of min-label propagation, keep components with 3+ accounts
CREATE OR REPLACE DYNAMIC TABLE RINGS TARGET_LAG='1 hour' WAREHOUSE=COMPUTE_WH AS
WITH e AS (SELECT ACCOUNT_A a, ACCOUNT_B b FROM RING_EDGES UNION ALL SELECT ACCOUNT_B, ACCOUNT_A FROM RING_EDGES),
l0 AS (SELECT DISTINCT a node, a lbl FROM e),
l1 AS (SELECT p.node, LEAST(p.lbl,MIN(q.lbl)) lbl FROM l0 p JOIN e ON e.a=p.node JOIN l0 q ON q.node=e.b GROUP BY p.node,p.lbl),
l2 AS (SELECT p.node, LEAST(p.lbl,MIN(q.lbl)) lbl FROM l1 p JOIN e ON e.a=p.node JOIN l1 q ON q.node=e.b GROUP BY p.node,p.lbl),
l3 AS (SELECT p.node, LEAST(p.lbl,MIN(q.lbl)) lbl FROM l2 p JOIN e ON e.a=p.node JOIN l2 q ON q.node=e.b GROUP BY p.node,p.lbl),
l4 AS (SELECT p.node, LEAST(p.lbl,MIN(q.lbl)) lbl FROM l3 p JOIN e ON e.a=p.node JOIN l3 q ON q.node=e.b GROUP BY p.node,p.lbl),
comp AS (SELECT lbl root, ARRAY_AGG(node) WITHIN GROUP (ORDER BY node) members FROM l4 GROUP BY lbl HAVING COUNT(*)>=3),
sv AS (SELECT DISTINCT l4.lbl root, re.SHARED_VALUE FROM RING_EDGES re JOIN l4 ON l4.node=re.ACCOUNT_A),
links AS (SELECT root, LISTAGG(SHARED_VALUE,', ') WITHIN GROUP (ORDER BY SHARED_VALUE) shared_link FROM sv GROUP BY root),
tx AS (SELECT sv.root, ARRAY_AGG(t.TRANSACTION_ID) WITHIN GROUP (ORDER BY t.TRANSACTION_ID) txn_ids, MAX(t.TRANSACTION_DATE) detected_at
       FROM sv JOIN l4 ON l4.lbl=sv.root JOIN TRANSACTIONS t ON t.ACCOUNT_ID=l4.node AND t.COUNTERPARTY_NAME=sv.SHARED_VALUE GROUP BY sv.root)
SELECT 'RING-'||LPAD(ROW_NUMBER() OVER (ORDER BY comp.root),3,'0') RING_ID, comp.members MEMBER_ACCOUNTS, links.shared_link SHARED_LINK, tx.txn_ids TRANSACTION_IDS, tx.detected_at DETECTED_AT
FROM comp JOIN links USING (root) JOIN tx USING (root);
