SELECT 'txn_count' k, TO_VARCHAR(COUNT(*)) v FROM VIGIL.CORE.TRANSACTIONS
UNION ALL SELECT 'accounts', TO_VARCHAR(COUNT(*)) FROM VIGIL.CORE.ACCOUNTS
UNION ALL SELECT 'alerts', TO_VARCHAR(COUNT(*)) FROM VIGIL.CORE.ALERTS
UNION ALL SELECT 'ring_edges', TO_VARCHAR(COUNT(*)) FROM VIGIL.CORE.RING_EDGES
UNION ALL SELECT 'ring_edge_counterparties', LISTAGG(DISTINCT SHARED_VALUE, ', ') FROM VIGIL.CORE.RING_EDGES
UNION ALL SELECT 'rings', TO_VARCHAR(COUNT(*)) FROM VIGIL.CORE.RINGS
UNION ALL SELECT 'ring_detail', RING_ID||' | '||ARRAY_TO_STRING(MEMBER_ACCOUNTS,',')||' | '||SHARED_LINK||' | '||ARRAY_TO_STRING(TRANSACTION_IDS,',') FROM VIGIL.CORE.RINGS
UNION ALL SELECT 'utility_in_rings', TO_VARCHAR(COUNT(*)) FROM VIGIL.CORE.RINGS WHERE SHARED_LINK ILIKE '%Electricity%'
UNION ALL SELECT 'lcr_breaches', LISTAGG(SNAPSHOT_DATE||'='||LCR_RATIO, ', ') FROM VIGIL.CORE.LIQUIDITY_SNAPSHOTS WHERE STATUS='BREACH'
UNION ALL SELECT 'npa', LISTAGG(LOAN_ACCOUNT_ID||' dpd='||DAYS_PAST_DUE, ', ') FROM VIGIL.CORE.CREDIT_PROFILES WHERE NPA_FLAG
UNION ALL SELECT 'structuring_sum', TO_VARCHAR(SUM(AMOUNT)) FROM VIGIL.CORE.TRANSACTIONS WHERE FLAG_REASON='STRUCTURING_SUSPECTED';
