USE SCHEMA VIGIL.CORE;
CREATE OR REPLACE TABLE POLICY_CLAUSES (DOC_ID STRING, CLAUSE_NO STRING, DOC_TITLE STRING, CLAUSE_TITLE STRING, CLAUSE_TEXT STRING, CITATION STRING);
INSERT INTO POLICY_CLAUSES (DOC_ID,CLAUSE_NO,DOC_TITLE,CLAUSE_TITLE,CLAUSE_TEXT,CITATION) VALUES
($$POL-AML-001$$,$$1.1$$,$$POL-AML-001 — Structuring & Smurfing Detection$$,$$Purpose$$,$$This policy defines how the bank identifies deposits deliberately split to avoid the cash reporting threshold.$$,$$POL-AML-001 Clause 1.1$$),
($$POL-AML-001$$,$$2.1$$,$$POL-AML-001 — Structuring & Smurfing Detection$$,$$Reporting Threshold$$,$$Cash transactions of INR 2,00,000 (₹2L) or more in a single transaction are subject to mandatory reporting.$$,$$POL-AML-001 Clause 2.1$$),
($$POL-AML-001$$,$$3.1$$,$$POL-AML-001 — Structuring & Smurfing Detection$$,$$Structuring Pattern Definition$$,$$Structuring is presumed when an account receives 3 or more cash deposits, each between ₹1,80,000 and ₹1,99,999, within any rolling 10-day window.$$,$$POL-AML-001 Clause 3.1$$),
($$POL-AML-001$$,$$3.2$$,$$POL-AML-001 — Structuring & Smurfing Detection$$,$$Aggregation$$,$$Deposits are aggregated per account. Deposits made across different channels or branches are aggregated together.$$,$$POL-AML-001 Clause 3.2$$),
($$POL-AML-001$$,$$4.1$$,$$POL-AML-001 — Structuring & Smurfing Detection$$,$$Escalation Timeline$$,$$A suspected structuring case must be escalated to the AML Compliance Officer within 24 hours of the alert being raised.$$,$$POL-AML-001 Clause 4.1$$),
($$POL-AML-001$$,$$4.2$$,$$POL-AML-001 — Structuring & Smurfing Detection$$,$$Evidentiary Standard$$,$$An escalation must cite the transaction IDs of every deposit in the pattern, their amounts and dates, and the account ID.$$,$$POL-AML-001 Clause 4.2$$),
($$POL-AML-001$$,$$4.5$$,$$POL-AML-001 — Structuring & Smurfing Detection$$,$$RING_PATTERN: Coordinated Account Activity$$,$$Three or more accounts transacting with the same counterparty or device within a 72-hour window, absent a legitimate shared business relationship, are presumptively treated as coordinated activity and require escalation within 24 hours. Counterparties that serve a legitimate broad customer base (for example utilities or government bodies) are excluded from this presumption. Evidence must cite the ring's member account IDs, the shared counterparty or device, and the transaction IDs involved.$$,$$POL-AML-001 Clause 4.5$$),
($$POL-AML-002$$,$$1.1$$,$$POL-AML-002 — High-Risk Jurisdiction Transactions$$,$$Purpose$$,$$This policy governs transactions with counterparties in jurisdictions the FATF identifies as high risk.$$,$$POL-AML-002 Clause 1.1$$),
($$POL-AML-002$$,$$2.1$$,$$POL-AML-002 — High-Risk Jurisdiction Transactions$$,$$Jurisdiction Definition$$,$$High-risk jurisdictions are those on the FATF grey list or black list. For this policy the monitored set includes Myanmar, North Korea, Iran and Panama.$$,$$POL-AML-002 Clause 2.1$$),
($$POL-AML-002$$,$$3.1$$,$$POL-AML-002 — High-Risk Jurisdiction Transactions$$,$$Enhanced Due Diligence$$,$$Any transaction of ₹5,00,000 (₹5L) or more to or from a high-risk jurisdiction requires Enhanced Due Diligence (EDD) before or at the time of processing.$$,$$POL-AML-002 Clause 3.1$$),
($$POL-AML-002$$,$$3.2$$,$$POL-AML-002 — High-Risk Jurisdiction Transactions$$,$$EDD Contents$$,$$EDD must record the purpose of the payment, the relationship to the counterparty, and the source of funds.$$,$$POL-AML-002 Clause 3.2$$),
($$POL-AML-002$$,$$4.1$$,$$POL-AML-002 — High-Risk Jurisdiction Transactions$$,$$Mandatory Escalation$$,$$A remittance meeting Clause 3.1 without a completed EDD record must be escalated to the AML Compliance Officer within 24 hours.$$,$$POL-AML-002 Clause 4.1$$),
($$POL-AML-002$$,$$4.2$$,$$POL-AML-002 — High-Risk Jurisdiction Transactions$$,$$Evidentiary Standard$$,$$The finding must cite the transaction ID, amount, counterparty name and country, and whether an EDD record exists.$$,$$POL-AML-002 Clause 4.2$$),
($$POL-AML-003$$,$$1.1$$,$$POL-AML-003 — Transaction Velocity Monitoring$$,$$Purpose$$,$$This policy addresses accounts used as pass-through channels, where funds arrive and leave almost immediately.$$,$$POL-AML-003 Clause 1.1$$),
($$POL-AML-003$$,$$2.1$$,$$POL-AML-003 — Transaction Velocity Monitoring$$,$$Velocity Pattern Definition$$,$$A velocity pattern exists when a deposit of ₹5,00,000 or more is followed within 24 hours by withdrawals or outgoing transfers totalling 80% or more of the deposit.$$,$$POL-AML-003 Clause 2.1$$),
($$POL-AML-003$$,$$3.1$$,$$POL-AML-003 — Transaction Velocity Monitoring$$,$$Automatic Hold$$,$$On detection, the bank may place an automatic hold on further outgoing transactions on the account pending review.$$,$$POL-AML-003 Clause 3.1$$),
($$POL-AML-003$$,$$4.1$$,$$POL-AML-003 — Transaction Velocity Monitoring$$,$$Escalation Timeline$$,$$A velocity case must be escalated to the AML Compliance Officer within 24 hours of detection.$$,$$POL-AML-003 Clause 4.1$$),
($$POL-AML-003$$,$$4.2$$,$$POL-AML-003 — Transaction Velocity Monitoring$$,$$Evidentiary Standard$$,$$The finding must cite the deposit transaction ID and each outgoing transaction ID, their amounts and timestamps, and the computed percentage moved.$$,$$POL-AML-003 Clause 4.2$$),
($$POL-AML-004$$,$$1.1$$,$$POL-AML-004 — STR Filing Timelines & KYC Obligations$$,$$Purpose$$,$$This policy sets the timeline for filing a Suspicious Transaction Report (STR) and the KYC conditions that affect it.$$,$$POL-AML-004 Clause 1.1$$),
($$POL-AML-004$$,$$2.1$$,$$POL-AML-004 — STR Filing Timelines & KYC Obligations$$,$$STR Filing Timeline$$,$$An STR must be filed with FIU-IND within 7 working days of the AML Compliance Officer concluding that a transaction is suspicious, consistent with PMLA Rule 8.$$,$$POL-AML-004 Clause 2.1$$),
($$POL-AML-004$$,$$2.2$$,$$POL-AML-004 — STR Filing Timelines & KYC Obligations$$,$$Human Sign-off$$,$$An STR is never filed automatically. A named compliance officer must review and approve every filing.$$,$$POL-AML-004 Clause 2.2$$),
($$POL-AML-004$$,$$3.1$$,$$POL-AML-004 — STR Filing Timelines & KYC Obligations$$,$$KYC Status Dependency$$,$$If the customer's KYC status is PENDING or EXPIRED, the case is escalated as a control deficiency in addition to the suspicious activity finding.$$,$$POL-AML-004 Clause 3.1$$),
($$POL-AML-004$$,$$3.2$$,$$POL-AML-004 — STR Filing Timelines & KYC Obligations$$,$$Risk-Segment Escalation$$,$$For customers in the HIGH risk segment, internal escalation deadlines are halved (24 hours becomes 12 hours).$$,$$POL-AML-004 Clause 3.2$$),
($$POL-AML-004$$,$$4.1$$,$$POL-AML-004 — STR Filing Timelines & KYC Obligations$$,$$Control Deficiency Reporting$$,$$Control deficiencies, such as expired KYC on an account with flagged activity, must be reported to the Head of Compliance in the same escalation.$$,$$POL-AML-004 Clause 4.1$$),
($$POL-CR-001$$,$$1.1$$,$$POL-CR-001 — NPA Classification & Provisioning$$,$$Purpose$$,$$This policy defines when a loan is classified as a Non-Performing Asset (NPA) and the provisioning required, following RBI IRAC norms.$$,$$POL-CR-001 Clause 1.1$$),
($$POL-CR-001$$,$$2.1$$,$$POL-CR-001 — NPA Classification & Provisioning$$,$$NPA Threshold$$,$$A loan account with more than 90 days past due is classified as an NPA.$$,$$POL-CR-001 Clause 2.1$$),
($$POL-CR-001$$,$$3.1$$,$$POL-CR-001 — NPA Classification & Provisioning$$,$$Sub-classification$$,$$- Substandard: NPA for up to 12 months.
- Doubtful: NPA for more than 12 months.
- Loss: an asset identified as uncollectible.$$,$$POL-CR-001 Clause 3.1$$),
($$POL-CR-001$$,$$3.2$$,$$POL-CR-001 — NPA Classification & Provisioning$$,$$Provisioning$$,$$- Substandard: 15% of the outstanding amount.
- Doubtful: 25% to 100% of the outstanding amount, depending on the period in the doubtful category.
- Loss: 100% of the outstanding amount.$$,$$POL-CR-001 Clause 3.2$$),
($$POL-CR-001$$,$$4.1$$,$$POL-CR-001 — NPA Classification & Provisioning$$,$$Evidentiary Standard$$,$$The finding must cite the loan account ID, days past due, outstanding amount, the classification and the provisioning amount calculated.$$,$$POL-CR-001 Clause 4.1$$),
($$POL-LIQ-001$$,$$1.1$$,$$POL-LIQ-001 — Basel III Liquidity Coverage Ratio (LCR) Compliance$$,$$Purpose$$,$$This policy sets the bank's minimum liquidity standard under Basel III.$$,$$POL-LIQ-001 Clause 1.1$$),
($$POL-LIQ-001$$,$$2.1$$,$$POL-LIQ-001 — Basel III Liquidity Coverage Ratio (LCR) Compliance$$,$$LCR Requirement$$,$$LCR = High Quality Liquid Assets (HQLA) ÷ Net Cash Outflows over the next 30 days. The bank must maintain an LCR of 100% or more at all times.$$,$$POL-LIQ-001 Clause 2.1$$),
($$POL-LIQ-001$$,$$3.1$$,$$POL-LIQ-001 — Basel III Liquidity Coverage Ratio (LCR) Compliance$$,$$Breach Classification$$,$$Any daily snapshot with LCR below 100% is classified as a BREACH.$$,$$POL-LIQ-001 Clause 3.1$$),
($$POL-LIQ-001$$,$$3.2$$,$$POL-LIQ-001 — Basel III Liquidity Coverage Ratio (LCR) Compliance$$,$$ALCO Escalation$$,$$A breach must be escalated to the Asset-Liability Committee (ALCO) within 4 hours of detection.$$,$$POL-LIQ-001 Clause 3.2$$),
($$POL-LIQ-001$$,$$4.1$$,$$POL-LIQ-001 — Basel III Liquidity Coverage Ratio (LCR) Compliance$$,$$Remediation Documentation$$,$$The bank must document the cause of the breach, the remediation actions and the expected date of return to compliance.$$,$$POL-LIQ-001 Clause 4.1$$),
($$POL-LIQ-001$$,$$4.2$$,$$POL-LIQ-001 — Basel III Liquidity Coverage Ratio (LCR) Compliance$$,$$Evidentiary Standard$$,$$The finding must cite the snapshot date, the HQLA amount, the net cash outflows and the computed LCR.$$,$$POL-LIQ-001 Clause 4.2$$);
SELECT (SELECT COUNT(*) FROM POLICY_CLAUSES) clauses, SNOWFLAKE.CORTEX.COMPLETE('llama3.1-8b','Reply with the single word OK') cortex_test;
