USE SCHEMA VIGIL.CORE;
CREATE OR REPLACE CORTEX SEARCH SERVICE POLICY_SEARCH
  ON CLAUSE_TEXT
  ATTRIBUTES DOC_ID, CLAUSE_NO, CITATION
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '1 day'
  AS (SELECT CLAUSE_TEXT, DOC_ID, CLAUSE_NO, CITATION, CLAUSE_TITLE FROM POLICY_CLAUSES);
SELECT (SELECT COUNT(*) FROM POLICY_CLAUSES) clauses;
