COPY INTO @VIGIL.CORE.APP_STAGE/environment.yml FROM (SELECT $$name: sf_env
channels:
  - snowflake
dependencies:
  - streamlit=1.35.0
$$) FILE_FORMAT=(TYPE=CSV COMPRESSION=NONE FIELD_DELIMITER=NONE RECORD_DELIMITER=NONE ESCAPE_UNENCLOSED_FIELD=NONE FIELD_OPTIONALLY_ENCLOSED_BY=NONE) SINGLE=TRUE OVERWRITE=TRUE HEADER=FALSE;
LIST @VIGIL.CORE.APP_STAGE;
